### ISSUE TITLE
Changes in parameters

### ISSUE THREAD

**Issue by nbfigueroa** [rajeshrinet/pyross#12]
Hello!

I've noticed that you changed the beta parameter in the "india" examples from beta=0.0155 (as in your paper) to beta  = 0.0298, is this estimate from new data? If so from when?

Thanks!

Btw, really like the paper.

Cheers!
Nadia

**Comment by rajeshrinet** [comment]
@nbfigueroa this is a good observation. We use the same data but different models.

In our paper, we have used the SIR model. In this new example, you are referring to now, we are using the SEIR model. Both these models have been fitted to the same data and since beta is a fitting parameter given all other parameters, it is natural for it to be different in the two cases as SEIR has more parameters than SIR. 

Thanks for your comments on your paper. Much appreciated.

Cheers, 
Rajesh
