### ISSUE TITLE
Exposure latency

### ISSUE THREAD

**Issue by Chinmaya-Kausik** [rajeshrinet/pyross#2]
I'm not sure, but it seems that adding exposure latency, and hence having an SE(Ia Ir)R model, would help. I'm asking here because this is one of the few models accounting for age-based social contact.

**Comment by ronojoy** [comment]
@Chinmaya-Kausik yes, we could add exposure latency, and have an E class, but that would only increase all the estimates we have made. The SIR compartmentalisation, with two types of infectives (asymptomatic and symptomatic) will give a lower bound, which is the "best case" scenario we have described. Note also, that we set asymptomatic cases to zero, since we have no idea how many such cases there are. This further reduces the bound, since there *are* asymptomatic cases, possibly much larger than the confirmed symptomatic cases.

**Comment by Chinmaya-Kausik** [comment]
Indeed, that is true. I was merely interested in what would happen if we try to increase accuracy. Also, you have probably seen this already (and it is of course probably not indicative of anything due to low sample sizes), but [here](https://eurosurveillance.org/content/10.2807/1560-7917.ES.2020.25.10.2000180) is an estimate for asymptomatic cases on the Diamond Princess. It may be somewhat illuminating to run it with alpha from here.

**Comment by rajeshrinet** [comment]
@Chinmaya-Kausik thanks for bringing it to our notice.
