### ISSUE TITLE
Any chance of adding asymptomatic?

### ISSUE THREAD

**Issue by philip-mach** [rajeshrinet/pyross#6]
[This paper](https://www.sciencedirect.com/science/article/pii/S0022519317305489) models the effect of asymptomatic transmission of dengue.

I am concerned that this is a big factor being missed as there are reports that asymptomatic could be as much as 50%. If you compare Germany with Italy and Spain, Germany has an order of magnitude fewer deaths / case and its ICUs are not being swamped. It has a much higher rate of testing too. The difference cannot only be accounted for by counting more actual cases. My hypothesis: by doing aggressive track and test, the Germans reduced the next wave of contagion from asymptomatic carriers.

**Comment by rajeshrinet** [comment]
@philip-mach thanks for sharing the paper. We already have the asymptomatic transmission in our model. We set the fraction to zero (alpha=0 in the [example](https://github.com/rajeshrinet/pyross/blob/master/examples/ex3-age-structured-SIR-for-India.ipynb))

alpha can be tuned based on the data.

**Comment by technOslerphile** [comment]
@rajeshrinet 
Two related questions:

1. If I add a non-zero 'alpha' parameter, then do the `india.txt` file need to be modified so that it reflects the number of cases that would include the confirmed cases + asymptomatic cases? I am asking because the current example simulations are all based on the assumption that 'alpha' is zero. 

2. The current covid case data in 'india.txt' is updated only till March 25th. We have two more weeks of data and do you think the model predictions will be more robust if we use the updated data (let's say till April 8th)? Forget about the non-pharmacological interventions (NPIs) that started in India on March 24th and which was basically the focus of your paper. My question is only with regard to whether having the current updated data would make the model forecasts more robust.  In this context, I am only interested in forecast and not effects of NPIs

**Comment by rajeshrinet** [comment]
@technOslerphile 

1. Yes, one needs to get estimates of asymptomatic cases or update india.txt so that true symptomatic and asymptomatic cases are listed. The parameter alpha can be modified but that means the fitting parameter beta has to be reevaluated.  

2. Yes, it is a good idea. I have not been able to do it myself because right now I am working on developing code for other models with more and more details. In our paper, we had only considered SIR model, but we now have SEIR, and other models.  So even for the same data, it provides a way to do the model comparison...

**Comment by technOslerphile** [comment]
@rajeshrinet 
1. We have some decent estimates of asymptomatic proportion of cases from certain 'randomly' sampled populations in Iceland, Diamond Princess ship and Italian municipality of Vo. 
https://medium.com/@dennis.robert.nm/how-deadly-is-covid-19-e80c973e2823
We would get better idea with serological testing being done more widely, but as of now about 50% seems to be a reasonable informed alpha. So I was thinking of using a range of alpha and see what happens. So when you say I have to update india.txt, do you mean to update the number of cases as well? I mean, for example, on March 25th, the # is 606. If we assume alpha is 0.5, then this number should be updated to 1212 [606 (symptomatic) + 606 (asymptomatic)] . Is my understanding correct? 
2. Got it. My question was just to clarify my doubt. You have already done quite enough!!! :-)

**Comment by rajeshrinet** [comment]
@technOslerphile in that sense, you want to partition all reported cases in symptomatic and asymptomatic cases. That should work as well.  This has to be reflected in initial number of symptomatic and asymptomatic cases for the simulations.
